import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { ActivityIndicator, Alert, Keyboard, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { getRoomFormData, getRooms, updateRoom } from "@/shared/services/RoomService";
import type { Cinema } from "@/shared/types/cinema";
import type { Room } from "@/shared/types/room";

export default function UpdateRoomScreen({ roomId }: { roomId: string }) {
  const router = useRouter(); const [room, setRoom] = useState<Room | null>(null); const [cinemas, setCinemas] = useState<Cinema[]>([]); const [cinemaId, setCinemaId] = useState(""); const [name, setName] = useState(""); const [rows, setRows] = useState(""); const [seats, setSeats] = useState(""); const [saving, setSaving] = useState(false); const [keyboardHeight, setKeyboardHeight] = useState(0); const scrollRef = useRef<ScrollView>(null);
  useEffect(() => { void Promise.all([getRooms(), getRoomFormData()]).then(([rooms, data]) => { const found = rooms.find((item) => item._id === roomId) ?? null; setRoom(found); setCinemas(data.cinemas ?? []); if (found) { setCinemaId(typeof found.cinemaId === "string" ? found.cinemaId : found.cinemaId._id); setName(found.roomName); setRows(String(found.rows)); setSeats(String(found.seatsPerRow)); } }).catch((error) => Alert.alert("Error", error instanceof Error ? error.message : "Cannot load room")); }, [roomId]);
  useEffect(() => { const show = Keyboard.addListener(Platform.OS === "ios" ? "keyboardWillShow" : "keyboardDidShow", (event) => setKeyboardHeight(event.endCoordinates.height)); const hide = Keyboard.addListener(Platform.OS === "ios" ? "keyboardWillHide" : "keyboardDidHide", () => setKeyboardHeight(0)); return () => { show.remove(); hide.remove(); }; }, []);
  const total = useMemo(() => Number(rows) * Number(seats) || 0, [rows, seats]);
  const save = async () => { if (!room || !cinemaId || !name.trim() || !Number(rows) || !Number(seats)) return Alert.alert("Missing information", "Please complete all fields."); setSaving(true); try { await updateRoom(room._id, { cinemaId, roomName:name.trim(), rows:Number(rows), seatsPerRow:Number(seats) }); router.replace("/admin/RoomsManagement"); } catch(error) { Alert.alert("Error", error instanceof Error ? error.message : "Cannot update room"); } finally { setSaving(false); } };
  if (!room) return <SafeAreaView style={styles.safe}><ActivityIndicator color="#E50914" /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.header}><Pressable onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={22} color="#FFF" /></Pressable><Text style={styles.title}>Update Room</Text></View><ScrollView ref={scrollRef} contentContainerStyle={[styles.content, { paddingBottom: keyboardHeight + 40 }]} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Cinema</Text><View style={styles.cinemas}>{cinemas.map((cinema) => <Pressable key={cinema._id} onPress={() => setCinemaId(cinema._id)} style={[styles.cinema, cinemaId === cinema._id && styles.active]}><Text style={styles.cinemaText}>{cinema.cinemaName}</Text></Pressable>)}</View><Text style={styles.label}>Room name</Text><TextInput value={name} onChangeText={setName} onFocus={() => setTimeout(() => scrollRef.current?.scrollTo({ y: 100, animated: true }), 100)} style={styles.input}/><View style={styles.row}><View style={styles.col}><Text style={styles.label}>Rows</Text><TextInput value={rows} onChangeText={setRows} onFocus={() => setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 100)} keyboardType="number-pad" style={styles.input}/></View><View style={styles.col}><Text style={styles.label}>Seats / row</Text><TextInput value={seats} onChangeText={setSeats} onFocus={() => setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 100)} keyboardType="number-pad" style={styles.input}/></View></View><Text style={styles.total}>Total seats: {total}</Text><Pressable onPress={() => void save()} disabled={saving} style={styles.save}><Text style={styles.saveText}>{saving ? "Saving..." : "Save changes"}</Text></Pressable></ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:"#0D141D",paddingHorizontal:16},header:{height:60,flexDirection:"row",alignItems:"center",gap:14},back:{width:38,height:38,borderRadius:19,backgroundColor:"#171E29",alignItems:"center",justifyContent:"center"},title:{color:"#FFF",fontSize:21,fontWeight:"800"},content:{paddingVertical:14,paddingBottom:40},label:{color:"#9AA3B2",fontWeight:"700",marginBottom:8},cinemas:{gap:8,marginBottom:18},cinema:{padding:13,borderRadius:10,backgroundColor:"#171E29",borderWidth:1,borderColor:"#222A36"},active:{borderColor:"#E50914",backgroundColor:"#3B1F25"},cinemaText:{color:"#FFF"},input:{height:48,backgroundColor:"#0D141D",borderColor:"#222A36",borderWidth:1,borderRadius:10,color:"#FFF",paddingHorizontal:12,marginBottom:16},row:{flexDirection:"row",gap:10},col:{flex:1},total:{color:"#E50914",fontWeight:"800",marginBottom:22},save:{backgroundColor:"#E50914",padding:16,alignItems:"center",borderRadius:10},saveText:{color:"#FFF",fontWeight:"800"}});
