import AsyncStorage from '@react-native-async-storage/async-storage';
import { MaterialIcons } from '@expo/vector-icons';
import * as WebBrowser from 'expo-web-browser';
import { Href, router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  Image,
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { createBooking, getBookingById, previewBooking } from '@/shared/services/BookingService';
import {
  Booking,
  BookingCheckout,
  MovieSummary,
  PaymentMethod,
  PriceSummary,
} from '@/shared/types/booking';

function encodeUtf8(input = '') {
  const bytes: number[] = [];

  for (let index = 0; index < input.length; index += 1) {
    let codePoint = input.charCodeAt(index);

    if (codePoint >= 0xd800 && codePoint <= 0xdbff && index + 1 < input.length) {
      const next = input.charCodeAt(index + 1);

      if (next >= 0xdc00 && next <= 0xdfff) {
        codePoint = 0x10000 + ((codePoint - 0xd800) << 10) + (next - 0xdc00);
        index += 1;
      }
    }

    if (codePoint <= 0x7f) {
      bytes.push(codePoint);
    } else if (codePoint <= 0x7ff) {
      bytes.push(0xc0 | (codePoint >> 6), 0x80 | (codePoint & 0x3f));
    } else if (codePoint <= 0xffff) {
      bytes.push(
        0xe0 | (codePoint >> 12),
        0x80 | ((codePoint >> 6) & 0x3f),
        0x80 | (codePoint & 0x3f),
      );
    } else {
      bytes.push(
        0xf0 | (codePoint >> 18),
        0x80 | ((codePoint >> 12) & 0x3f),
        0x80 | ((codePoint >> 6) & 0x3f),
        0x80 | (codePoint & 0x3f),
      );
    }
  }

  return new Uint8Array(bytes);
}

const textEncoderGlobal = globalThis as any;

if (!textEncoderGlobal.TextEncoder) {
  textEncoderGlobal.TextEncoder = class {
    encode(input = '') {
      return encodeUtf8(input);
    }
  };
}

const { toQR } = require('toqr') as {
  toQR: (content: string | Uint8Array, ec?: number) => Uint8Array;
};

const TEST_TOKEN = '';
const TEST_SHOWTIME_ID = '';
const TEST_SEAT_IDS: string[] = [];
const QR_QUIET_ZONE = 4;
const PAYMENT_POLL_INTERVAL_MS = 5000;

const demoCheckout: BookingCheckout = {
  movie: {
    _id: 'demo-movie',
    title: 'Interstellar Odyssey',
    genre: 'Sci-Fi',
    duration: 148,
    rating: 4.9,
    poster:
      'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  },
  showtime: {
    _id: 'demo-showtime',
    showDate: '2024-10-24T00:00:00.000Z',
    startTime: '20:45',
    endTime: '23:13',
    price: 90000,
  },
  cinema: {
    _id: 'demo-cinema',
    cinemaName: 'Grand Cinema',
    address: '7th Ave, New York',
    city: 'New York',
  },
  room: {
    _id: 'demo-room',
    roomName: 'Hall 04',
  },
  selectedSeats: [
    {
      _id: 'demo-seat-1',
      seatRow: 'G',
      seatNumber: 12,
      seatType: 'vip',
      seatName: 'G12',
      price: 90000,
    },
    {
      _id: 'demo-seat-2',
      seatRow: 'G',
      seatNumber: 14,
      seatType: 'vip',
      seatName: 'G14',
      price: 90000,
    },
  ],
  priceSummary: {
    orderAmount: 180000,
    serviceFee: 2500,
    discountAmount: 0,
    totalPrice: 182500,
    promoCode: '',
  },
};

function getParamValue(value?: string | string[]) {
  if (Array.isArray(value)) {
    return value[0] || '';
  }

  return value || '';
}

function parseSeatIds(value?: string | string[]) {
  const rawValue = getParamValue(value);

  if (!rawValue) {
    return TEST_SEAT_IDS;
  }

  return rawValue
    .split(',')
    .map((seatId) => seatId.trim())
    .filter(Boolean);
}

function formatCurrency(value: number) {
  return `${Math.round(value).toLocaleString('vi-VN')} VND`;
}

function formatDate(value?: string) {
  if (!value) {
    return 'N/A';
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function formatGenre(movie?: MovieSummary | null) {
  if (!movie || !movie.genre) {
    return 'Cinema';
  }

  return Array.isArray(movie.genre) ? movie.genre.join(', ') : movie.genre;
}

function getPosterUrl(movie?: MovieSummary | null) {
  return movie?.poster || movie?.posterUrl || demoCheckout.movie?.poster || '';
}

function getPayosDescription(orderCode?: number) {
  if (!orderCode) {
    return 'Generated by PayOS';
  }

  return `CB${String(orderCode).slice(-7)}`;
}

function formatCountdown(expiresAt?: string) {
  if (!expiresAt) {
    return '15:00';
  }

  const remainingSeconds = Math.max(
    0,
    Math.floor((new Date(expiresAt).getTime() - Date.now()) / 1000),
  );
  const minutes = Math.floor(remainingSeconds / 60);
  const seconds = remainingSeconds % 60;

  return `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;
}

function buildQrRows(value: string) {
  if (!value) {
    return [];
  }

  try {
    const rawMatrix = toQR(value, 1);
    const moduleCount = Math.sqrt(rawMatrix.length);

    if (!Number.isInteger(moduleCount)) {
      return [];
    }

    const totalCount = moduleCount + QR_QUIET_ZONE * 2;

    return Array.from({ length: totalCount }, (_, rowIndex) =>
      Array.from({ length: totalCount }, (_, columnIndex) => {
        const sourceRow = rowIndex - QR_QUIET_ZONE;
        const sourceColumn = columnIndex - QR_QUIET_ZONE;

        if (
          sourceRow < 0 ||
          sourceColumn < 0 ||
          sourceRow >= moduleCount ||
          sourceColumn >= moduleCount
        ) {
          return false;
        }

        return rawMatrix[sourceRow * moduleCount + sourceColumn] === 1;
      }),
    );
  } catch {
    return [];
  }
}

function applyDemoPromo(priceSummary: PriceSummary, promoCode: string): PriceSummary {
  const normalizedCode = promoCode.trim().toUpperCase();
  let discountAmount = 0;
  let promoMessage = '';

  if (normalizedCode === 'CINEMA10') {
    discountAmount = Math.round(priceSummary.orderAmount * 0.1);
    promoMessage = 'Promo CINEMA10 applied';
  } else if (normalizedCode === 'NEWUSER') {
    discountAmount = Math.min(5000, priceSummary.orderAmount);
    promoMessage = 'Promo NEWUSER applied';
  } else if (normalizedCode) {
    promoMessage = 'Promo code is not valid';
  }

  return {
    ...priceSummary,
    promoCode: normalizedCode,
    discountAmount,
    promoMessage,
    totalPrice: Math.max(
      0,
      Math.round((priceSummary.orderAmount + priceSummary.serviceFee - discountAmount) * 100) /
        100,
    ),
  };
}

export default function PaymentScreen() {
  const params = useLocalSearchParams<{
    token?: string;
    showtimeId?: string;
    seatIds?: string;
  }>();
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('payos');
  const [promoCode, setPromoCode] = useState('');
  const [checkout, setCheckout] = useState<BookingCheckout>(demoCheckout);
  const [bookingId, setBookingId] = useState('');
  const [paymentUrl, setPaymentUrl] = useState('');
  const [paymentQrCode, setPaymentQrCode] = useState('');
  const [paymentOrderCode, setPaymentOrderCode] = useState<number | undefined>();
  const [paymentExpiresAt, setPaymentExpiresAt] = useState('');
  const [paymentStatus, setPaymentStatus] = useState('');
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [countdown, setCountdown] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [storedToken, setStoredToken] = useState('');
  const ticketRedirectedRef = useRef(false);

  const token = getParamValue(params.token) || storedToken || TEST_TOKEN;
  const showtimeId = getParamValue(params.showtimeId) || TEST_SHOWTIME_ID;
  const seatIds = useMemo(() => parseSeatIds(params.seatIds), [params.seatIds]);
  const canUseApi = Boolean(token && showtimeId && seatIds.length > 0);
  const movie = checkout.movie;
  const selectedSeatNames = checkout.selectedSeats.map((seat) => seat.seatName).join(', ');
  const hasPaymentSession = Boolean(bookingId || paymentUrl || paymentQrCode);
  const isPaymentPaid = paymentStatus === 'paid';
  const isPaymentFailed = paymentStatus === 'failed' || paymentStatus === 'cancelled';
  const isPaymentTerminal =
    paymentStatus === 'paid' || paymentStatus === 'failed' || paymentStatus === 'cancelled';
  const isPaymentPending = hasPaymentSession && !isPaymentTerminal;
  const payosDescription = getPayosDescription(paymentOrderCode);

  const resetPaymentSession = useCallback(() => {
    ticketRedirectedRef.current = false;
    setBookingId('');
    setPaymentUrl('');
    setPaymentQrCode('');
    setPaymentOrderCode(undefined);
    setPaymentExpiresAt('');
    setPaymentStatus('');
    setCountdown('');
  }, []);

  const loadPreview = async (nextPromoCode = promoCode) => {
    setError('');
    setMessage('');
    resetPaymentSession();

    if (!canUseApi) {
      setCheckout((currentCheckout) => ({
        ...currentCheckout,
        priceSummary: applyDemoPromo(currentCheckout.priceSummary, nextPromoCode),
      }));
      return;
    }

    setIsLoadingPreview(true);

    try {
      const preview = await previewBooking(
        {
          showtimeId,
          seatIds,
          promoCode: nextPromoCode,
        },
        token,
      );

      setCheckout(preview);
      setMessage(preview.priceSummary.promoMessage || '');
    } catch (previewError) {
      const nextError =
        previewError instanceof Error ? previewError.message : 'Failed to load payment preview';
      setError(nextError);
    } finally {
      setIsLoadingPreview(false);
    }
  };

  useEffect(() => {
    AsyncStorage.getItem('token')
      .then((nextToken) => setStoredToken(nextToken || ''))
      .catch(() => setStoredToken(''));
  }, []);

  useEffect(() => {
    loadPreview('');
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [token, showtimeId, seatIds.join(',')]);

  const handleApplyPromo = () => {
    loadPreview(promoCode);
  };

  const openPaymentUrl = async (url: string) => {
    if (!url) {
      return;
    }

    await WebBrowser.openBrowserAsync(url);
  };

  const openTickets = useCallback(() => {
    router.replace({
      pathname: '/my-ticket',
      params: token ? { token } : {},
    } as Href);
  }, [token]);

  const syncPaymentFromBooking = useCallback(
    (booking: Booking) => {
      setBookingId(booking._id);
      setPaymentStatus(booking.paymentStatus);
      setPaymentExpiresAt(booking.paymentExpiresAt || '');
      setPaymentOrderCode(booking.payosOrderCode || undefined);
      setPaymentUrl((currentUrl) => booking.payosCheckoutUrl || currentUrl);
      setPaymentQrCode((currentQrCode) => booking.payosQrCode || currentQrCode);

      if (booking.paymentStatus === 'paid' && booking.bookingStatus === 'confirmed') {
        setMessage(`Payment confirmed. Ticket code: ${booking.ticketCode}`);
        setError('');

        if (!ticketRedirectedRef.current) {
          ticketRedirectedRef.current = true;
          setTimeout(openTickets, 900);
        }
      }

      if (booking.paymentStatus === 'failed' || booking.bookingStatus === 'cancelled') {
        setError('Payment expired or cancelled. Please choose seats and create a new payment.');
      }
    },
    [openTickets],
  );

  const checkPaymentStatus = useCallback(
    async () => {
      if (!bookingId || !token) {
        return;
      }

      try {
        const booking = await getBookingById(bookingId, token);
        syncPaymentFromBooking(booking);
      } catch (paymentCheckError) {
        console.log('Payment polling failed', paymentCheckError);
      }
    },
    [bookingId, syncPaymentFromBooking, token],
  );

  useEffect(() => {
    if (!paymentExpiresAt) {
      return;
    }

    setCountdown(formatCountdown(paymentExpiresAt));

    const timerId = setInterval(() => {
      setCountdown(formatCountdown(paymentExpiresAt));
    }, 1000);

    return () => {
      clearInterval(timerId);
    };
  }, [paymentExpiresAt]);

  useEffect(() => {
    if (!isPaymentPending || !bookingId || !token) {
      return;
    }

    checkPaymentStatus();

    const pollId = setInterval(() => {
      checkPaymentStatus();
    }, PAYMENT_POLL_INTERVAL_MS);

    return () => {
      clearInterval(pollId);
    };
  }, [bookingId, checkPaymentStatus, isPaymentPending, token]);

  const handleConfirm = async () => {
    setError('');
    setMessage('');

    if (isPaymentPaid) {
      openTickets();
      return;
    }

    if (isPaymentFailed) {
      resetPaymentSession();
      setMessage('Payment expired or cancelled. Create a new VietQR payment when ready.');
      return;
    }

    if (hasPaymentSession) {
      return;
    }

    if (!canUseApi) {
      setError('Missing token, showtimeId, or seatIds. Payment is showing demo data.');
      return;
    }

    setIsProcessing(true);

    try {
      const result = await createBooking(
        {
          showtimeId,
          seatIds,
          paymentMethod,
          promoCode,
        },
        token,
      );

      setCheckout(result.checkout);
      syncPaymentFromBooking(result.booking);

      if (result.payment?.provider === 'payos' && result.payment.checkoutUrl) {
        setPaymentUrl(result.payment.checkoutUrl);
        setPaymentQrCode(result.payment.qrCode || result.booking.payosQrCode || '');
        setPaymentOrderCode(result.payment.orderCode || result.booking.payosOrderCode || undefined);
        setPaymentExpiresAt(
          String(result.payment.expiresAt || result.booking.paymentExpiresAt || ''),
        );
        setPaymentStatus(result.payment.status || result.booking.paymentStatus);
        setMessage('VietQR payment created. Scan the QR below and keep this screen open.');
        return;
      }

      if (result.booking.paymentStatus === 'paid') {
        setMessage(`Payment success. Ticket code: ${result.booking.ticketCode}`);
        openTickets();
      } else {
        setMessage('Booking created. Waiting for payment confirmation.');
      }
    } catch (bookingError) {
      const nextError =
        bookingError instanceof Error ? bookingError.message : 'Failed to confirm booking';
      setError(nextError);
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.header}>
        <Pressable style={styles.iconButton} onPress={() => router.back()}>
          <MaterialIcons name="arrow-back" size={24} color="#dce3f0" />
        </Pressable>

        <Text style={styles.headerTitle}>Confirm Booking</Text>

        <View style={styles.iconButton} />
      </View>

      <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
        <View style={styles.movieRow}>
          <View style={styles.posterWrap}>
            <Image source={{ uri: getPosterUrl(movie) }} style={styles.poster} />
            <Text style={styles.posterBadge}>IMAX</Text>
          </View>

          <View style={styles.movieInfo}>
            <Text style={styles.movieTitle}>{movie?.title || 'Movie title'}</Text>
            <Text style={styles.metaText}>
              {formatGenre(movie)} - {movie?.duration || 0} min - {movie?.rating || 'N/A'}
            </Text>
          </View>
        </View>

        <View style={styles.card}>
          <View style={styles.cardHeaderRow}>
            <View style={styles.cardHeaderText}>
              <Text style={styles.label}>Cinema & Location</Text>
              <Text style={styles.value}>
                {checkout.cinema?.cinemaName || 'Cinema'} - {checkout.room?.roomName || 'Room'}
              </Text>
              <Text style={styles.metaText}>{checkout.cinema?.address || 'Address'}</Text>
            </View>
            <MaterialIcons name="map" size={24} color="#e50914" />
          </View>

          <View style={styles.detailsGrid}>
            <View style={styles.detailColumn}>
              <Text style={styles.label}>Showtime</Text>
              <Text style={styles.value}>{formatDate(checkout.showtime.showDate)}</Text>
              <Text style={styles.highlightValue}>{checkout.showtime.startTime}</Text>
            </View>

            <View style={[styles.detailColumn, styles.leftBorder]}>
              <Text style={styles.label}>Seats</Text>
              <Text style={styles.value}>
                {checkout.selectedSeats[0]?.seatType === 'vip' ? 'VIP Section' : 'Standard'}
              </Text>
              <Text style={styles.highlightValue}>{selectedSeatNames || 'N/A'}</Text>
            </View>
          </View>
        </View>

        <View style={styles.card}>
          <Text style={styles.label}>Promo Code</Text>
          <View style={styles.promoRow}>
            <TextInput
              placeholder="Enter code"
              placeholderTextColor="#777"
              value={promoCode}
              onChangeText={setPromoCode}
              autoCapitalize="characters"
              editable={!paymentUrl}
              style={styles.input}
            />
            <Pressable
              style={[
                styles.applyButton,
                (isLoadingPreview || Boolean(paymentUrl)) && styles.disabledButton,
              ]}
              onPress={handleApplyPromo}
              disabled={isLoadingPreview || Boolean(paymentUrl)}>
              <Text style={styles.applyText}>{isLoadingPreview ? '...' : 'Apply'}</Text>
            </Pressable>
          </View>
        </View>

        <View style={styles.card}>
          <Text style={styles.label}>Payment Method</Text>

          <PaymentOption
            label="VietQR / PayOS"
            badge="QR"
            selected={paymentMethod === 'payos'}
            onPress={() => setPaymentMethod('payos')}
          />
        </View>

        <View style={styles.card}>
          <PriceRow
            label={`Order Amount (${checkout.selectedSeats.length} seats)`}
            value={formatCurrency(checkout.priceSummary.orderAmount)}
          />
          <PriceRow label="Service Fee" value={formatCurrency(checkout.priceSummary.serviceFee)} />
          <PriceRow
            label="Promo Discount"
            value={`-${formatCurrency(checkout.priceSummary.discountAmount)}`}
            accent
          />
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total Pay</Text>
            <Text style={styles.total}>{formatCurrency(checkout.priceSummary.totalPrice)}</Text>
          </View>
        </View>

        {hasPaymentSession && (
          <View style={[styles.card, styles.qrCard]}>
            <View style={styles.qrHeaderRow}>
              <View>
                <Text style={styles.label}>VietQR Payment</Text>
                <Text style={styles.qrTitle}>
                  {isPaymentPaid
                    ? 'Payment confirmed'
                    : isPaymentFailed
                      ? 'Payment expired'
                      : 'Scan to pay'}
                </Text>
              </View>

              <View
                style={[
                  styles.statusPill,
                  isPaymentPaid && styles.statusPillPaid,
                  isPaymentFailed && styles.statusPillFailed,
                ]}>
                <MaterialIcons
                  name={isPaymentPaid ? 'check-circle' : isPaymentFailed ? 'error' : 'schedule'}
                  size={16}
                  color={isPaymentPaid ? '#0f5132' : '#fff7f6'}
                />
                <Text
                  style={[
                    styles.statusText,
                    isPaymentPaid && styles.statusTextPaid,
                  ]}>
                  {isPaymentPaid ? 'Paid' : isPaymentFailed ? 'Expired' : countdown || 'Pending'}
                </Text>
              </View>
            </View>

            <View style={styles.qrPanel}>
              {paymentQrCode ? (
                <PayosQrCode value={paymentQrCode} />
              ) : (
                <View style={styles.qrFallback}>
                  <MaterialIcons name="qr-code-2" size={68} color="#e50914" />
                  <Text style={styles.qrFallbackText}>
                    QR is not available. Open PayOS checkout instead.
                  </Text>
                </View>
              )}
            </View>

            <Text style={styles.qrInstruction}>
              Open your banking app, scan this VietQR, and transfer the exact amount.
              This screen updates automatically after PayOS confirms payment.
            </Text>

            <View style={styles.paymentMetaBox}>
              <PaymentMeta label="Amount" value={formatCurrency(checkout.priceSummary.totalPrice)} />
              <PaymentMeta label="Content" value={payosDescription} />
              <PaymentMeta
                label="Order"
                value={paymentOrderCode ? String(paymentOrderCode) : 'Pending'}
              />
            </View>

            {paymentUrl ? (
              <View style={styles.paymentActions}>
                <Pressable style={styles.secondaryButton} onPress={() => openPaymentUrl(paymentUrl)}>
                  <MaterialIcons name="open-in-new" size={18} color="#fff7f6" />
                  <Text style={styles.secondaryButtonText}>Open PayOS</Text>
                </Pressable>
              </View>
            ) : null}
          </View>
        )}

        {!!message && <Text style={styles.successText}>{message}</Text>}
        {!!error && <Text style={styles.errorText}>{error}</Text>}
      </ScrollView>

      <View style={styles.bottomBar}>
        <Pressable
          style={[
            styles.confirmButton,
            (isProcessing || isPaymentPending) && styles.disabledButton,
          ]}
          onPress={handleConfirm}
          disabled={isProcessing || isPaymentPending}>
          <Text style={styles.confirmText}>
            {isPaymentPaid
              ? 'View Ticket'
              : isPaymentFailed
                ? 'Create New Payment'
              : hasPaymentSession
                ? 'Waiting for payment...'
                : isProcessing
                  ? 'Creating...'
                  : 'Create VietQR Payment'}
          </Text>
          {!isProcessing && <MaterialIcons name="chevron-right" size={24} color="#fff7f6" />}
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

function PaymentOption({
  label,
  badge,
  icon,
  selected,
  onPress,
}: {
  label: string;
  badge?: string;
  icon?: keyof typeof MaterialIcons.glyphMap;
  selected: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      style={[styles.paymentOption, selected && styles.paymentSelected]}
      onPress={onPress}>
      <View style={styles.paymentLeft}>
        <View style={[styles.paymentIcon, badge && styles.momoIcon]}>
          {badge ? (
            <Text style={styles.paymentBadge}>{badge}</Text>
          ) : (
            <MaterialIcons name={icon || 'payments'} size={22} color="#dce3f0" />
          )}
        </View>
        <Text style={styles.value}>{label}</Text>
      </View>

      <MaterialIcons
        name={selected ? 'radio-button-checked' : 'radio-button-unchecked'}
        size={22}
        color={selected ? '#e50914' : '#c8c6c5'}
      />
    </Pressable>
  );
}

function PriceRow({
  label,
  value,
  accent,
}: {
  label: string;
  value: string;
  accent?: boolean;
}) {
  return (
    <View style={styles.priceRow}>
      <Text style={[styles.priceLabel, accent && styles.accentText]}>{label}</Text>
      <Text style={[styles.priceValue, accent && styles.accentText]}>{value}</Text>
    </View>
  );
}

function PaymentMeta({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.paymentMetaItem}>
      <Text style={styles.paymentMetaLabel}>{label}</Text>
      <Text style={styles.paymentMetaValue} numberOfLines={2}>
        {value}
      </Text>
    </View>
  );
}

function PayosQrCode({ value }: { value: string }) {
  const rows = useMemo(() => buildQrRows(value), [value]);

  if (!rows.length) {
    return (
      <View style={styles.qrFallback}>
        <MaterialIcons name="qr-code-2" size={68} color="#e50914" />
        <Text style={styles.qrFallbackText}>Unable to render QR code.</Text>
      </View>
    );
  }

  return (
    <View style={styles.qrMatrix}>
      {rows.map((row, rowIndex) => (
        <View key={`qr-row-${rowIndex}`} style={styles.qrRow}>
          {row.map((isDark, columnIndex) => (
            <View
              key={`qr-cell-${rowIndex}-${columnIndex}`}
              style={[styles.qrCell, isDark && styles.qrCellDark]}
            />
          ))}
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0d141d',
  },
  header: {
    height: 64,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  iconButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    color: '#fff7f6',
    fontSize: 20,
    fontWeight: '700',
  },
  content: {
    padding: 20,
    paddingBottom: 120,
  },
  movieRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 24,
  },
  posterWrap: {
    width: 96,
    height: 144,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#151c25',
  },
  poster: {
    width: '100%',
    height: '100%',
  },
  posterBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: '#e50914',
    color: '#fff7f6',
    fontSize: 10,
    fontWeight: '800',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  movieInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  movieTitle: {
    color: '#dce3f0',
    fontSize: 24,
    fontWeight: '700',
  },
  metaText: {
    color: '#af8782',
    marginTop: 4,
  },
  card: {
    backgroundColor: '#192029',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  cardHeaderText: {
    flex: 1,
  },
  detailsGrid: {
    flexDirection: 'row',
    gap: 16,
    paddingTop: 16,
  },
  detailColumn: {
    flex: 1,
  },
  leftBorder: {
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.05)',
    paddingLeft: 16,
  },
  label: {
    color: '#af8782',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  value: {
    color: '#dce3f0',
    fontSize: 16,
    fontWeight: '600',
  },
  highlightValue: {
    color: '#fff7f6',
    fontSize: 18,
    fontWeight: '800',
    marginTop: 4,
  },
  promoRow: {
    flexDirection: 'row',
    gap: 8,
  },
  input: {
    flex: 1,
    backgroundColor: '#151c25',
    borderRadius: 12,
    color: '#dce3f0',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
  },
  applyButton: {
    backgroundColor: '#2e353f',
    borderRadius: 12,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  applyText: {
    color: '#dce3f0',
    fontWeight: '600',
  },
  paymentOption: {
    padding: 14,
    borderRadius: 12,
    backgroundColor: '#232a34',
    marginTop: 10,
    borderWidth: 1,
    borderColor: 'transparent',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  paymentSelected: {
    borderColor: '#e50914',
    backgroundColor: '#2e353f',
  },
  paymentLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  paymentIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  momoIcon: {
    backgroundColor: '#a50064',
  },
  paymentBadge: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  priceLabel: {
    color: '#af8782',
    fontSize: 15,
  },
  priceValue: {
    color: '#dce3f0',
    fontSize: 15,
    fontWeight: '600',
  },
  accentText: {
    color: '#e50914',
  },
  totalRow: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.08)',
    paddingTop: 14,
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalLabel: {
    color: '#fff7f6',
    fontSize: 20,
    fontWeight: '800',
  },
  total: {
    color: '#fff7f6',
    fontSize: 28,
    fontWeight: '800',
  },
  qrCard: {
    gap: 14,
  },
  qrHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  qrTitle: {
    color: '#fff7f6',
    fontSize: 22,
    fontWeight: '800',
  },
  statusPill: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#e50914',
  },
  statusPillPaid: {
    backgroundColor: '#d1fae5',
  },
  statusPillFailed: {
    backgroundColor: '#7f1d1d',
  },
  statusText: {
    color: '#fff7f6',
    fontSize: 12,
    fontWeight: '800',
  },
  statusTextPaid: {
    color: '#0f5132',
  },
  qrPanel: {
    alignSelf: 'center',
    width: '82%',
    maxWidth: 292,
    aspectRatio: 1,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qrMatrix: {
    width: '100%',
    height: '100%',
    backgroundColor: '#ffffff',
  },
  qrRow: {
    flex: 1,
    flexDirection: 'row',
  },
  qrCell: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  qrCellDark: {
    backgroundColor: '#111827',
  },
  qrFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  qrFallbackText: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 8,
  },
  qrInstruction: {
    color: '#c8c6c5',
    fontSize: 13,
    lineHeight: 20,
    textAlign: 'center',
  },
  paymentMetaBox: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    overflow: 'hidden',
  },
  paymentMetaItem: {
    minHeight: 54,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.08)',
  },
  paymentMetaLabel: {
    color: '#af8782',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  paymentMetaValue: {
    color: '#fff7f6',
    fontSize: 15,
    fontWeight: '800',
  },
  paymentActions: {
    flexDirection: 'row',
    gap: 10,
  },
  secondaryButton: {
    flex: 1,
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: '#2e353f',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  secondaryButtonText: {
    color: '#fff7f6',
    fontSize: 14,
    fontWeight: '700',
  },
  successText: {
    color: '#67d391',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
  },
  errorText: {
    color: '#ffb4ab',
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 16,
  },
  bottomBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: 20,
    backgroundColor: 'rgba(13, 20, 29, 0.96)',
    borderTopWidth: 1,
    borderTopColor: 'rgba(255, 255, 255, 0.05)',
  },
  confirmButton: {
    height: 56,
    borderRadius: 16,
    backgroundColor: '#e50914',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  confirmText: {
    color: '#fff7f6',
    fontSize: 18,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.65,
  },
});
